[package]
name = "ntru"
version = "0.1.0"
edition = "2021"
authors = ["sv512"]
description = "Simple & insecure NTRUEncrypt CLI"
license = "GPL-3.0-only"
license-file = "LICENSE.txt"

[dependencies]
ntru = "0.5.6"
base64 = "0.13.1"
structopt = "0.3.26"
